name: ci

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: Y
          MSSQL_SA_PASSWORD: Your_strong_Password123
        ports:
          - 14333:1433
        options: >-
          --health-cmd "SQLCMD=$$(find /opt/mssql-tools* -path '*/bin/sqlcmd' | head -n 1); [ -n \"$$SQLCMD\" ] && $$SQLCMD -S localhost -U sa -P \"$$MSSQL_SA_PASSWORD\" -C -Q 'SELECT 1'"
          --health-interval 15s
          --health-timeout 10s
          --health-retries 10

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.200
      - name: Restore
        run: dotnet restore PromoEngine.sln
      - name: Build
        run: dotnet build PromoEngine.sln -c Release --no-restore
      - name: Test
        env:
          ConnectionStrings__SqlServer: Server=localhost,14333;Database=PromoEngine;User Id=sa;Password=Your_strong_Password123;TrustServerCertificate=True;Encrypt=False
        run: dotnet test PromoEngine.sln -c Release --no-build
